### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by pastorhudson** [deanmcgregor/ynab-python#3]
When running in python 3.7 and following the setup instructions I run the example code and get:

```
C:\Users\rhudson\PycharmProjects\ynab-oled\venv\Scripts\python.exe C:/Users/rhudson/PycharmProjects/ynab-oled/groceries.py
Traceback (most recent call last):
  File "C:/Users/rhudson/PycharmProjects/ynab-oled/groceries.py", line 3, in <module>
    import ynab
  File "C:\Users\rhudson\PycharmProjects\ynab-oled\venv\lib\site-packages\ynab\__init__.py", line 19, in <module>
    from ynab.ynab.accounts_api import AccountsApi
  File "C:\Users\rhudson\PycharmProjects\ynab-oled\venv\lib\site-packages\ynab\ynab\__init__.py", line 6, in <module>
    from ynab.ynab.accounts_api import AccountsApi
  File "C:\Users\rhudson\PycharmProjects\ynab-oled\venv\lib\site-packages\ynab\ynab\accounts_api.py", line 133
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```
It seems async is a reserved keyword.

**Comment by pastorhudson** [comment]
Thank You!

**Comment by NejcZupec** [comment]
Thank you for this fix. Works like a charm :)
